### PR TITLE
fix(verb): corrected exposure for AdaptiveRefinementNode and AdaptiveRefinementOptions

### LINKED ISSUE #61: Invalid name space for AdaptiveRefinementOptions and AdaptiveRefinementNode
It seems that these two class ere present in src/eva/Tess.hx

But are exposed as 'core'

```
@:expose("core.AdaptiveRefinementOptions")
@:expose("core.AdaptiveRefinementNode")

```

The documentation says 'eval'.

### PR DESCRIPTION
**Pull request by z3dev**
These are small changes to the exposures. It was kind of frustrating to not find the documented classes.

New build as well for version 3.0.1

fixes #61

### CODE REVIEW

**Comment by z3dev** [comment]
@pboyer Please review. This is a small fix so there shouldn't be any issues. Let me know if a test case should be created.

Also, can you publish to NPM?

**Comment by z3dev** [comment]
@pboyer The reason that I'm making these changes is for JSCAD users. JSCAD doesn't have the NURBS primitives, and this library works perfectly with the JSCAD model.

www.OpenJSCAD.xyz

**Comment by z3dev** [comment]
@pboyer What do you think? Are these changes good?

**Comment by pboyer** [comment]
Hey @z3dev, 

This looks good. Apologies for the delay, I just got back from vacation. Let me see if I can publish this new version. It's been a while.

**Comment by z3dev** [comment]
@pboyer i believes that it should just be build followed by publish. But authentication to NOM has changed, so you might find a few gotchas

**Comment by z3dev** [comment]
@pboyer This is huge! The first release after 8 years! I can't believe it... this library is rock solid but needs a little care.

**Comment by z3dev** [comment]
@pboyer Please let me know if there is any thing that I can assist. I'd be glad to publish but then it would not be the official version of verb. :(

**Comment by pboyer** [comment]
Sorry for the delay on publishing. As you mentioned, NPM's authentication process changed and I learned that gmail classifies my emails from npm as phishing.

**Pull request merged**
