### PR TITLE
fixes to versions and new build of JS packages for 3.0.3

### PR DESCRIPTION
**Pull request by z3dev**
As the title says.

### CODE REVIEW

**Comment by z3dev** [comment]
@pboyer this is the new JS packages for 3.0.3. Sorry. I should have created those previously.

**Comment by z3dev** [comment]
@pboyer please release

**Review by pboyer — APPROVED** [review]

**Comment by z3dev** [comment]
@pboyer thanks for the merger, but it doesn't matter much unless you publish to NPM. 🙇‍♀️

**Comment by pboyer** [comment]
Just published. Let me know if you see any issues!

**Pull request merged**
